### ISSUE TITLE
ask some questions

### ISSUE THREAD

**Issue by 943fansi** [dongtsi/OWAD#1]
1. I did not find the reading link of this paper, and I am very interested in the content of the article.
2. I come from another job of yours, DeepAID, can you tell me the connection and difference between these two jobs?
3. Is this method suitable for anomaly detection in time series?

Looking forward to your answer.

**Comment by dongtsi** [comment]
Thanks for your insterest! ^v^
1. I think the paper will be released soon as the conference will be held at the end of Feb.
2. Both DeepAID and OWAD can be used for zero-positive DL-based anomaly detection. DeepAID aims to explain the black-box DL model and tell user why a certain anomaly is determined (aka interpretability), while OWAD tackles concept drift problem (distribution changes from training to test set) and tell user how to remedy the model (aka robustness).
3. Yes. Both DeepAID and OWAD can be used for anomaly detection in time series. DeepAID is primarily used for univariate anoamly detection, while OWAD is not necessarily contrained to univariate.

**Comment by 943fansi** [comment]
@dongtsi Thank you very much for your reply.
I don't quite understand the term `zero-positive DL-based anomaly detection`, which means we only use normal data for modeling?

**Comment by dongtsi** [comment]
Yes! zero-positive means that we only use normal data for training the deep learning model and detect deviation as anomalies (aslo known as unsupervised anomaly detection). An example is to use autoencoder to reconstrut normal data with less error during training and report anomalies if reconstrut error is more than a certain threshold. You could refer to section 2.2 of DeepAID paper for more details.

**Comment by 943fansi** [comment]
Thanks.

**Comment by Kihy** [comment]
Hello, I also have a question regarding the terminology: OWAD is supposedly unsupervised; however, during the calibration stage, it calculates the FPR, which requires label information, so why is it unsupervised?
