### ISSUE TITLE
the original dataset(Anoshift) has 20 features,but you supple the dataset which has 499 dimensions.how to change 

### ISSUE THREAD

**Issue by 1180300309** [dongtsi/OWAD#4]

**Comment by dongtsi** [comment]
Anoshift used one-hot encoding for categorical features in the Kyoto dataset. Please refer to their original implementation such as  [here](https://github.com/bit-ml/AnoShift/blob/main/baselines_ID_setup/load_anoshift.py).

**Comment by 1180300309** [comment]
Could you please answer two questions
1.In the examples you provided for 2007 and 2011, the number of datasets is inconsistent with the original dataset. Are we integrating the datasets from 2006-2010, 2011-2013 separately
2. During the process of one-hot encoding, should you remove features with smaller standard deviation

**Comment by dongtsi** [comment]
> Could you please answer two questions 1.In the examples you provided for 2007 and 2011, the number of datasets is inconsistent with the original dataset. Are we integrating the datasets from 2006-2010, 2011-2013 separately 2. During the process of one-hot encoding, should you remove features with smaller standard deviation

1. Our data split is different from the method in Anoshift. We split the dataset 10 times as `@T0`, `@T1,` ...`@T10` (to conduct multiple adaptation experiments). Please find more details in our paper.
2. What do you mean by "features with smaller standard deviation"? Do you mean the feature value after encoding (but they are all 0s or 1s)? I think we didn't do that.

**Comment by 1180300309** [comment]
May I ask how the original log data was processed into the example presented in your code in the second log dataset

- 1117838570 2005.06.03 R02-M1-N0-C:J12-U11 2005-06-03-15.42.50.675872 R02-M1-N0-C:J12-U11 RAS KERNEL INFO instruction cache parity error corrected

X_ic, X_oc, y_c = con_seq['input'], con_seq['output'], con_seq['label']

**Comment by dongtsi** [comment]
Do you mean the DeepLog dataset? You could use the processed log key sequence instead of raw logs, e.g., [here](https://github.com/Thijsvanede/DeepLog/tree/master/examples/data).
